name    'puppet-locations'
version '0.2.1'
source 'https://github.com/liquidautumn/puppet-locations'
author 'John Doe'
license 'Apache License, Version 2.0'
summary 'Module for detecting server location by ip address'
description 'Module for detecting server location by ip address'
project_page 'https://github.com/liquidautumn/puppet-locations'
